#!/usr/bin/env bash
#  ███████╗███╗   ███╗██╗██╗     ██╗ █████╗     ██████╗ ██╗ ██████╗███████╗
#  ██╔════╝████╗ ████║██║██║     ██║██╔══██╗    ██╔══██╗██║██╔════╝██╔════╝
#  █████╗  ██╔████╔██║██║██║     ██║███████║    ██████╔╝██║██║     █████╗
#  ██╔══╝  ██║╚██╔╝██║██║██║     ██║██╔══██║    ██╔══██╗██║██║     ██╔══╝
#  ███████╗██║ ╚═╝ ██║██║███████╗██║██║  ██║    ██║  ██║██║╚██████╗███████╗
#  ╚══════╝╚═╝     ╚═╝╚═╝╚══════╝╚═╝╚═╝  ╚═╝    ╚═╝  ╚═╝╚═╝ ╚═════╝╚══════╝
#  Author  :  z0mbi3
#  Url     :  https://github.com/gh0stzk/dotfiles
#  About   :  This file will configure and launch the rice.
#

# Set bspwm configuration for Emilia
set_bspwm_config() {
	bspc config border_width 0
	bspc config top_padding 56
	bspc config bottom_padding 2
	bspc config left_padding 2
	bspc config right_padding 2
	bspc config normal_border_color "#414868"
	bspc config active_border_color "#d4be98"
	bspc config focused_border_color "#d3869b"
	bspc config presel_feedback_color "#7daea3"
}

# Set alacritty colorscheme
set_alacritty_config() {
	cat >"$HOME"/.config/alacritty/rice-colors.toml <<EOF
# (Tokyo Night) color scheme for Emilia Rice

# Default colors
[colors.primary]
background = "#32302f"
foreground = "#d4be98"

# Cursor colors
[colors.cursor]
cursor = "#d4be98"
text = "#32302f"

# Normal colors
[colors.normal]
black = "#32302f"
blue = "#7daea3"
cyan = "#89b482"
green = "#a9b665"
magenta = "#d3869b"
red = "#ea6962"
white = "#a9b1d6"
yellow = "#e78a4e"

# Bright colors
[colors.bright]
black = "#414868"
blue = "#7daea3"
cyan = "#89b482"
green = "#a9b665"
magenta = "#d3869b"
red = "#ea6962"
white = "#d4be98"
yellow = "#e78a4e"
EOF
}

# Set kitty colorscheme
set_kitty_config() {
  cat >"$HOME"/.config/kitty/current-theme.conf <<EOF
## This file is autogenerated, do not edit it, instead edit the Theme.sh file inside the rice directory.
## (Tokyo Night) color scheme for Emilia Rice


# The basic colors
foreground              #d4be98
background              #32302f
selection_foreground    #24273A
selection_background    #F4DBD6

# Cursor colors
cursor                  #d4be98
cursor_text_color       #32302f

# URL underline color when hovering with mouse
url_color               #7daea3

# Kitty window border colors
active_border_color     #d3869b
inactive_border_color   #414868
bell_border_color       #e78a4e

# Tab bar colors
active_tab_foreground   #32302f
active_tab_background   #d3869b
inactive_tab_foreground #a9b1d6
inactive_tab_background #32302f
tab_bar_background      #32302f

# The 16 terminal colors

# black
color0 #32302f
color8 #414868

# red
color1 #ea6962
color9 #ea6962

# green
color2  #a9b665
color10 #a9b665

# yellow
color3  #e78a4e
color11 #e78a4e

# blue
color4  #7daea3
color12 #7daea3

# magenta
color5  #d3869b
color13 #d3869b

# cyan
color6  #89b482
color14 #89b482

# white
color7  #a9b1d6
color15 #d4be98
EOF

killall -USR1 kitty
}

# Set compositor configuration
set_picom_config() {
	sed -i "$HOME"/.config/bspwm/picom.conf \
		-e "s/normal = .*/normal =  { fade = true; shadow = true; }/g" \
		-e "s/shadow-color = .*/shadow-color = \"#000000\"/g" \
		-e "s/corner-radius = .*/corner-radius = 6/g" \
		-e "s/\".*:class_g = 'Alacritty'\"/\"100:class_g = 'Alacritty'\"/g" \
		-e "s/\".*:class_g = 'kitty'\"/\"100:class_g = 'kitty'\"/g" \
		-e "s/\".*:class_g = 'FloaTerm'\"/\"100:class_g = 'FloaTerm'\"/g"
}

# Set dunst notification daemon config
set_dunst_config() {
	sed -i "$HOME"/.config/bspwm/dunstrc \
		-e "s/transparency = .*/transparency = 0/g" \
		-e "s/frame_color = .*/frame_color = \"#a9b665\"/g" \
		-e "s/separator_color = .*/separator_color = \"#d4be98\"/g" \
		-e "s/font = .*/font = JetBrainsMono NF Medium 9/g" \
		-e "s/foreground='.*'/foreground='#f9f9f9'/g"

	sed -i '/urgency_low/Q' "$HOME"/.config/bspwm/dunstrc
	cat >>"$HOME"/.config/bspwm/dunstrc <<-_EOF_
		[urgency_low]
		timeout = 3
		background = "#1d2021"
		foreground = "#d4be98"

		[urgency_normal]
		timeout = 6
		background = "#32302f"
		foreground = "#d4be98"

		[urgency_critical]
		timeout = 0
		background = "#32302f"
		foreground = "#d4be98"
	_EOF_
}

# Set eww colors
set_eww_colors() {
	cat >"$HOME"/.config/bspwm/eww/colors.scss <<EOF
// Eww colors for Emilia rice
\$bg: #32302f;
\$bg-alt: #222330;
\$fg: #d4be98;
\$black: #414868;
\$lightblack: #262831;
\$red: #ea6962;
\$blue: #7daea3;
\$cyan: #89b482;
\$magenta: #d3869b;
\$green: #a9b665;
\$yellow: #e78a4e;
\$archicon: #0f94d2;
EOF
}

# Set jgmenu colors for Emilia
set_jgmenu_colors() {
	sed -i "$HOME"/.config/bspwm/jgmenurc \
		-e 's/color_menu_bg = .*/color_menu_bg = #32302f/' \
		-e 's/color_norm_fg = .*/color_norm_fg = #d4be98/' \
		-e 's/color_sel_bg = .*/color_sel_bg = #222330/' \
		-e 's/color_sel_fg = .*/color_sel_fg = #d4be98/' \
		-e 's/color_sep_fg = .*/color_sep_fg = #414868/'
}

# Set Rofi launcher config
set_launcher_config() {
	sed -i "$HOME/.config/bspwm/scripts/Launcher.rasi" \
		-e '22s/\(font: \).*/\1"JetBrainsMono NF Bold 9";/' \
		-e 's/\(background: \).*/\1#32302f;/' \
		-e 's/\(background-alt: \).*/\1#282828;/' \
		-e 's/\(foreground: \).*/\1#d4be98;/' \
		-e 's/\(selected: \).*/\1#ea6962;/' \
		-e "s/rices\/[[:alnum:]\-]*/rices\/${RICETHEME}/g"

	# NetworkManager launcher
	sed -i "$HOME/.config/bspwm/scripts/NetManagerDM.rasi" \
		-e '12s/\(background: \).*/\1#32302f;/' \
		-e '13s/\(background-alt: \).*/\1#282828;/' \
		-e '14s/\(foreground: \).*/\1#d4be98;/' \
		-e '15s/\(selected: \).*/\1#ea6962;/' \
		-e '16s/\(active: \).*/\1#a9b665;/' \
		-e '17s/\(urgent: \).*/\1#ea6962;/'

	# WallSelect menu colors
	sed -i "$HOME/.config/bspwm/scripts/WallSelect.rasi" \
		-e 's/\(main-bg: \).*/\1#32302f;/' \
		-e 's/\(main-fg: \).*/\1#d4be98;/' \
		-e 's/\(select-bg: \).*/\1#ea6962;/' \
		-e 's/\(select-fg: \).*/\1#d4be98;/'
}

# Launch the bar
launch_bars() {

	for mon in $(polybar --list-monitors | cut -d":" -f1); do
		MONITOR=$mon polybar -q emi-bar -c "${rice_dir}"/config.ini &
	done

}

### ---------- Apply Configurations ---------- ###

set_bspwm_config
set_alacritty_config
set_kitty_config
set_picom_config
launch_bars
set_eww_colors
set_jgmenu_colors
set_dunst_config
set_launcher_config
